# -*- coding: UTF-8 -*-
__author__ = 'Joynice'

from config import config
config = config['development']
BROKER_URL = config.HOST_SCAN_CELERY_BROKER_URL
CELERY_RESULT_BACKEND = config.HOST_SCAN_CELERY_RESULT_BACKEND

BROKER_URL = BROKER_URL

CELERY_RESULT_BACKEND = CELERY_RESULT_BACKEND
CELERY_TASK_SERIALIZER = "msgpack"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_RESULT_EXPIRES = 0
CELERY_ACCEPT_CONTENT = ['json','msgpack']
CELERYD_MAX_TASKS_PER_CHILD = 200
CELERY_MAX_RETRIES = 3
CELERY_MONGODB_BACKEND_SETTINGS = {
    "taskmeta_collection" : "celery"
}

CELERY_TIMEZONE = "Asia/Shanghai"