"""empty message

Revision ID: 25e8ffbd797a
Revises: d185f6851199
Create Date: 2019-04-10 15:46:30.943374

"""

# revision identifiers, used by Alembic.
revision = '25e8ffbd797a'
down_revision = 'd185f6851199'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'asset', ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asset', type_='unique')
    # ### end Alembic commands ###
