"""empty message

Revision ID: 5bc2fb3c59a1
Revises: 986441a5c20d
Create Date: 2019-04-12 10:27:03.207690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5bc2fb3c59a1'
down_revision = '986441a5c20d'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('hit_num', sa.Integer(), nullable=False))
    op.add_column('asset', sa.Column('url', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'asset', ['url'])
    op.drop_constraint('asset_ibfk_1', 'asset', type_='foreignkey')
    op.drop_column('asset', 'url_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('url_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('asset_ibfk_1', 'asset', 'task', ['url_id'], ['id'])
    op.drop_constraint(None, 'asset', type_='unique')
    op.drop_column('asset', 'url')
    op.drop_column('asset', 'hit_num')
    ### end Alembic commands ###
