"""empty message

Revision ID: 70a9d2e904eb
Revises: fb16b0b4849c
Create Date: 2019-04-26 10:58:28.197358

"""

# revision identifiers, used by Alembic.
revision = '70a9d2e904eb'
down_revision = 'fb16b0b4849c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'telephone',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'telephone',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=11),
               nullable=False)
    # ### end Alembic commands ###
