"""empty message

Revision ID: 79b64b96c408
Revises: 8104bab375af
Create Date: 2019-04-24 11:14:59.874299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b64b96c408'
down_revision = '8104bab375af'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('upgrade_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'upgrade_time')
    ### end Alembic commands ###
