"""empty message

Revision ID: 8104bab375af
Revises: 5bc2fb3c59a1
Create Date: 2019-04-15 08:33:52.144262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8104bab375af'
down_revision = '5bc2fb3c59a1'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'hit_num')
    op.add_column('cms_fingerprint', sa.Column('hit_num', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_fingerprint', 'hit_num')
    op.add_column('asset', sa.Column('hit_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    ### end Alembic commands ###
