"""empty message

Revision ID: afd9b3d2d0c3
Revises: None
Create Date: 2019-04-06 11:15:22.619112

"""

# revision identifiers, used by Alembic.
revision = 'afd9b3d2d0c3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_fingerprint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('re', sa.String(length=100), nullable=True),
    sa.Column('md5', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('result_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('cycle', sa.Enum('Cycle.ONEDAY', 'Cycle.THREEDAY', 'Cycle.WEEK', 'Cycle.HALF_MONTH', 'Cycle.ONEMONTH'), nullable=True),
    sa.Column('task_time', sa.DateTime(), nullable=True),
    sa.Column('next_time', sa.String(length=1000), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('State.WAIT_SCAN', 'State.ING_SCAN', 'State.FINISH_SCAN'), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('html', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=11), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('_password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('realname', sa.String(length=20), nullable=True),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('signature', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.Enum('GenderEnum.MALE', 'GenderEnum.FEMALE', 'GenderEnum.SECRET', 'GenderEnum.UNKNOW'), nullable=True),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telephone')
    )
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_id', sa.Integer(), nullable=True),
    sa.Column('webapp', sa.String(length=255), nullable=True),
    sa.Column('os', sa.String(length=255), nullable=True),
    sa.Column('server', sa.String(length=255), nullable=True),
    sa.Column('framework', sa.String(length=255), nullable=True),
    sa.Column('component', sa.String(length=255), nullable=True),
    sa.Column('waf', sa.String(length=255), nullable=True),
    sa.Column('cms', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset')
    op.drop_table('user')
    op.drop_table('task')
    op.drop_table('cms_fingerprint')
    # ### end Alembic commands ###
