"""empty message

Revision ID: de3f068c83f3
Revises: eca647832ddf
Create Date: 2019-04-10 11:27:01.019410

"""

# revision identifiers, used by Alembic.
revision = 'de3f068c83f3'
down_revision = 'eca647832ddf'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cms_fingerprint', 'hit_num',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cms_fingerprint', 'hit_num',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
