"""empty message

Revision ID: eca647832ddf
Revises: 0138e20bd617
Create Date: 2019-04-10 11:24:31.776453

"""

# revision identifiers, used by Alembic.
revision = 'eca647832ddf'
down_revision = '0138e20bd617'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_fingerprint', sa.Column('hit_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_fingerprint', 'hit_num')
    # ### end Alembic commands ###
