"""empty message

Revision ID: f4731725216f
Revises: 5fee48373a23
Create Date: 2019-03-26 14:48:10.796446

"""

# revision identifiers, used by Alembic.
revision = 'f4731725216f'
down_revision = '5fee48373a23'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cms_fingerprint', 'url',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cms_fingerprint', 'url',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=255),
               nullable=False)
    # ### end Alembic commands ###
